### ISSUE TITLE
Modal window not animating

### ISSUE THREAD

**Issue by jahvi** [vwall/compass-twitter-bootstrap#7]
Hi, first of all great extension I've been playing around with it for a couple hours and noticed the modal window wasn't animating right, I looked at the code and noticed an `e()` mixing in the `.fade` class here:

https://github.com/vwall/compass-twitter-bootstrap/blob/master/stylesheets/compass_twitter_bootstrap/_patterns.scss#L803

I was wondering what it does since it's not getting compiled right and the css ends up like:

``` css
.modal.fade {
  -webkit-transition: e("opacity .3s linear, top .3s ease-out");
  -moz-transition: e("opacity .3s linear, top .3s ease-out");
  -ms-transition: e("opacity .3s linear, top .3s ease-out");
  -o-transition: e("opacity .3s linear, top .3s ease-out");
  transition: e("opacity .3s linear, top .3s ease-out");
  top: -25%;
}
```

**Comment by jahvi** [comment]
Actually if you replace `@include transition(e('opacity .3s linear, top .3s ease-out'));` with `@include transition(unquote('opacity .3s linear, top .3s ease-out'));` it fixes, which is what you were trying to accomplish I believe.

**Comment by vwall** [comment]
Thanks.  I'll fix this this weekend.

**Comment by jahvi** [comment]
Looks like this issue is happening again, the [transition mixin](https://github.com/vwall/compass-twitter-bootstrap/blob/master/stylesheets_sass/compass_twitter_bootstrap/_mixins.sass#L173) should be `unquote`'d else the compiled function will look like:

``` css
.modal.fade { 
    -webkit-transition: "opacity .3s linear, top .3s ease-out";
    -moz-transition: "opacity .3s linear, top .3s ease-out";
    -ms-transition: "opacity .3s linear, top .3s ease-out";
    -o-transition: "opacity .3s linear, top .3s ease-out";
    transition: "opacity .3s linear, top .3s ease-out";
    top: -25%;
}
```
